version: "2"

services:
  server:
    image: server:1.0.0
    container_name: server
    ports:
      - 8000:8000
    env_file:
      - /home/jpardosi/Projects/docker/users/IRENE_SERVER.env

  scraping:
    image: scraping:1.0.0
    container_name: scraping
    cap_add:
      - SYS_ADMIN
    environment:
      POST_URL: http://server:8000/jobs
    env_file:
      - /home/jpardosi/Projects/docker/users/IRENE_SCRAPING.env
    restart: on-failure
    command: "node jobs.js"
